// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: network.proto

#include "network.pb.h"
#include "network.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace nn_proto {

static const char* NNTrainer_method_names[] = {
  "/nn_proto.NNTrainer/RunModel",
};

std::unique_ptr< NNTrainer::Stub> NNTrainer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< NNTrainer::Stub> stub(new NNTrainer::Stub(channel, options));
  return stub;
}

NNTrainer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RunModel_(NNTrainer_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status NNTrainer::Stub::RunModel(::grpc::ClientContext* context, const ::nn_proto::TrainRequest& request, ::nn_proto::TrainResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::nn_proto::TrainRequest, ::nn_proto::TrainResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RunModel_, context, request, response);
}

void NNTrainer::Stub::async::RunModel(::grpc::ClientContext* context, const ::nn_proto::TrainRequest* request, ::nn_proto::TrainResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::nn_proto::TrainRequest, ::nn_proto::TrainResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RunModel_, context, request, response, std::move(f));
}

void NNTrainer::Stub::async::RunModel(::grpc::ClientContext* context, const ::nn_proto::TrainRequest* request, ::nn_proto::TrainResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RunModel_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::nn_proto::TrainResponse>* NNTrainer::Stub::PrepareAsyncRunModelRaw(::grpc::ClientContext* context, const ::nn_proto::TrainRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::nn_proto::TrainResponse, ::nn_proto::TrainRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RunModel_, context, request);
}

::grpc::ClientAsyncResponseReader< ::nn_proto::TrainResponse>* NNTrainer::Stub::AsyncRunModelRaw(::grpc::ClientContext* context, const ::nn_proto::TrainRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRunModelRaw(context, request, cq);
  result->StartCall();
  return result;
}

NNTrainer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NNTrainer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NNTrainer::Service, ::nn_proto::TrainRequest, ::nn_proto::TrainResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](NNTrainer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::nn_proto::TrainRequest* req,
             ::nn_proto::TrainResponse* resp) {
               return service->RunModel(ctx, req, resp);
             }, this)));
}

NNTrainer::Service::~Service() {
}

::grpc::Status NNTrainer::Service::RunModel(::grpc::ServerContext* context, const ::nn_proto::TrainRequest* request, ::nn_proto::TrainResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace nn_proto
#include <grpcpp/ports_undef.inc>

