// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: network.proto
#ifndef GRPC_network_2eproto__INCLUDED
#define GRPC_network_2eproto__INCLUDED

#include "network.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace nn_proto {

// ---- gRPC 服务定义 ----
class NNTrainer final {
 public:
  static constexpr char const* service_full_name() {
    return "nn_proto.NNTrainer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status RunModel(::grpc::ClientContext* context, const ::nn_proto::TrainRequest& request, ::nn_proto::TrainResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nn_proto::TrainResponse>> AsyncRunModel(::grpc::ClientContext* context, const ::nn_proto::TrainRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nn_proto::TrainResponse>>(AsyncRunModelRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nn_proto::TrainResponse>> PrepareAsyncRunModel(::grpc::ClientContext* context, const ::nn_proto::TrainRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nn_proto::TrainResponse>>(PrepareAsyncRunModelRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void RunModel(::grpc::ClientContext* context, const ::nn_proto::TrainRequest* request, ::nn_proto::TrainResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RunModel(::grpc::ClientContext* context, const ::nn_proto::TrainRequest* request, ::nn_proto::TrainResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nn_proto::TrainResponse>* AsyncRunModelRaw(::grpc::ClientContext* context, const ::nn_proto::TrainRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nn_proto::TrainResponse>* PrepareAsyncRunModelRaw(::grpc::ClientContext* context, const ::nn_proto::TrainRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status RunModel(::grpc::ClientContext* context, const ::nn_proto::TrainRequest& request, ::nn_proto::TrainResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nn_proto::TrainResponse>> AsyncRunModel(::grpc::ClientContext* context, const ::nn_proto::TrainRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nn_proto::TrainResponse>>(AsyncRunModelRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nn_proto::TrainResponse>> PrepareAsyncRunModel(::grpc::ClientContext* context, const ::nn_proto::TrainRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nn_proto::TrainResponse>>(PrepareAsyncRunModelRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void RunModel(::grpc::ClientContext* context, const ::nn_proto::TrainRequest* request, ::nn_proto::TrainResponse* response, std::function<void(::grpc::Status)>) override;
      void RunModel(::grpc::ClientContext* context, const ::nn_proto::TrainRequest* request, ::nn_proto::TrainResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::nn_proto::TrainResponse>* AsyncRunModelRaw(::grpc::ClientContext* context, const ::nn_proto::TrainRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::nn_proto::TrainResponse>* PrepareAsyncRunModelRaw(::grpc::ClientContext* context, const ::nn_proto::TrainRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RunModel_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RunModel(::grpc::ServerContext* context, const ::nn_proto::TrainRequest* request, ::nn_proto::TrainResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RunModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RunModel() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RunModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunModel(::grpc::ServerContext* /*context*/, const ::nn_proto::TrainRequest* /*request*/, ::nn_proto::TrainResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRunModel(::grpc::ServerContext* context, ::nn_proto::TrainRequest* request, ::grpc::ServerAsyncResponseWriter< ::nn_proto::TrainResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RunModel<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_RunModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RunModel() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::nn_proto::TrainRequest, ::nn_proto::TrainResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::nn_proto::TrainRequest* request, ::nn_proto::TrainResponse* response) { return this->RunModel(context, request, response); }));}
    void SetMessageAllocatorFor_RunModel(
        ::grpc::MessageAllocator< ::nn_proto::TrainRequest, ::nn_proto::TrainResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::nn_proto::TrainRequest, ::nn_proto::TrainResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RunModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunModel(::grpc::ServerContext* /*context*/, const ::nn_proto::TrainRequest* /*request*/, ::nn_proto::TrainResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RunModel(
      ::grpc::CallbackServerContext* /*context*/, const ::nn_proto::TrainRequest* /*request*/, ::nn_proto::TrainResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_RunModel<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RunModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RunModel() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RunModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunModel(::grpc::ServerContext* /*context*/, const ::nn_proto::TrainRequest* /*request*/, ::nn_proto::TrainResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RunModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RunModel() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RunModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunModel(::grpc::ServerContext* /*context*/, const ::nn_proto::TrainRequest* /*request*/, ::nn_proto::TrainResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRunModel(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RunModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RunModel() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RunModel(context, request, response); }));
    }
    ~WithRawCallbackMethod_RunModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunModel(::grpc::ServerContext* /*context*/, const ::nn_proto::TrainRequest* /*request*/, ::nn_proto::TrainResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RunModel(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RunModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RunModel() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::nn_proto::TrainRequest, ::nn_proto::TrainResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::nn_proto::TrainRequest, ::nn_proto::TrainResponse>* streamer) {
                       return this->StreamedRunModel(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RunModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RunModel(::grpc::ServerContext* /*context*/, const ::nn_proto::TrainRequest* /*request*/, ::nn_proto::TrainResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRunModel(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::nn_proto::TrainRequest,::nn_proto::TrainResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RunModel<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RunModel<Service > StreamedService;
};

}  // namespace nn_proto


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_network_2eproto__INCLUDED
