// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: network.proto
// Protobuf C++ Version: 7.36.0-dev

#ifndef network_2eproto_2epb_2eh
#define network_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7036000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_network_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_network_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_network_2eproto;
}  // extern "C"
namespace nn_proto {
enum ActivationType : int;
extern const uint32_t ActivationType_internal_data_[];
class Layer;
struct LayerGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern LayerGlobalsTypeInternal Layer_globals_;
extern const ::google::protobuf::internal::ClassDataFull Layer_class_data_;
#else
extern const LayerGlobalsTypeInternal Layer_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class Network;
struct NetworkGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern NetworkGlobalsTypeInternal Network_globals_;
extern const ::google::protobuf::internal::ClassDataFull Network_class_data_;
#else
extern const NetworkGlobalsTypeInternal Network_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class WeightMetrix;
struct WeightMetrixGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern WeightMetrixGlobalsTypeInternal WeightMetrix_globals_;
extern const ::google::protobuf::internal::ClassDataFull WeightMetrix_class_data_;
#else
extern const WeightMetrixGlobalsTypeInternal WeightMetrix_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
}  // namespace nn_proto
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::nn_proto::ActivationType_internal_data_>
    internal::EnumTraitsImpl::value<::nn_proto::ActivationType>;
}  // namespace protobuf
}  // namespace google

namespace nn_proto {
enum ActivationType : int {
  ACT_ORIGIN = 0,
  ACT_RELU = 1,
  ACT_SIGMOID = 2,
  ACT_SOFTMAX = 3,
  ACT_LAYERNORM = 4,
  ACT_NONE = 5,
  ActivationType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  ActivationType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t ActivationType_internal_data_[];
inline constexpr ActivationType ActivationType_MIN =
    static_cast<ActivationType>(0);
inline constexpr ActivationType ActivationType_MAX =
    static_cast<ActivationType>(5);
[[nodiscard]] inline bool ActivationType_IsValid(int value) {
  return 0 <= value && value <= 5;
}
inline constexpr int ActivationType_ARRAYSIZE = 5 + 1;
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
ActivationType_descriptor();
[[nodiscard]] inline auto ProtobufInternalGetEnumDescriptor(ActivationType) {
  return ActivationType_descriptor();
}
template <typename T>
[[nodiscard]] const ::std::string& ActivationType_Name(T value) {
  static_assert(::std::is_same<T, ActivationType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to ActivationType_Name().");
  return ActivationType_Name(static_cast<ActivationType>(value));
}
template <>
[[nodiscard]] inline const ::std::string& ActivationType_Name(ActivationType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ActivationType_descriptor, 0, 5>(
      static_cast<int>(value));
}
[[nodiscard]] inline bool ActivationType_Parse(
    ::absl::string_view name, ActivationType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<ActivationType>(ActivationType_descriptor(), name,
                                           value);
}
using ::google::protobuf::internal::generated_enum::AbslParseFlag;
using ::google::protobuf::internal::generated_enum::AbslUnparseFlag;

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED WeightMetrix final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:nn_proto.WeightMetrix) */ {
 public:
  inline WeightMetrix() : WeightMetrix(nullptr) {}
  ~WeightMetrix() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(WeightMetrix* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(WeightMetrix));
  }
#endif

  template <typename = void>
  explicit constexpr WeightMetrix(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline WeightMetrix(const WeightMetrix& from) : WeightMetrix(nullptr, from) {}
  inline WeightMetrix(WeightMetrix&& from) noexcept : WeightMetrix(nullptr, ::std::move(from)) {}
  inline WeightMetrix& operator=(const WeightMetrix& from) {
    CopyFrom(from);
    return *this;
  }
  inline WeightMetrix& operator=(WeightMetrix&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const WeightMetrix& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<WeightMetrix>(&WeightMetrix_globals_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(WeightMetrix& a, WeightMetrix& b) { a.Swap(&b); }
  inline void Swap(WeightMetrix* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WeightMetrix* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] WeightMetrix* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<WeightMetrix>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const WeightMetrix& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const WeightMetrix& from) { WeightMetrix::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(WeightMetrix* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "nn_proto.WeightMetrix"; }

  explicit WeightMetrix(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  WeightMetrix(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const WeightMetrix& from);
  WeightMetrix(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, WeightMetrix&& from) noexcept
      : WeightMetrix(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDataFieldNumber = 3,
    kRowsFieldNumber = 1,
    kColsFieldNumber = 2,
  };
  // bytes data = 3;
  void clear_data() ;
  [[nodiscard]] const ::std::string& data() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_data(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_data();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_data();
  void set_allocated_data(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_data() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_data(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_data();

  public:
  // int32 rows = 1;
  void clear_rows() ;
  [[nodiscard]] ::int32_t rows() const;
  void set_rows(::int32_t value);

  private:
  ::int32_t _internal_rows() const;
  void _internal_set_rows(::int32_t value);

  public:
  // int32 cols = 2;
  void clear_cols() ;
  [[nodiscard]] ::int32_t cols() const;
  void set_cols(::int32_t value);

  private:
  ::int32_t _internal_cols() const;
  void _internal_set_cols(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:nn_proto.WeightMetrix)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<2, 3,
                          0, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const WeightMetrix& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr data_;
    ::int32_t rows_;
    ::int32_t cols_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_network_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED Layer final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:nn_proto.Layer) */ {
 public:
  inline Layer() : Layer(nullptr) {}
  ~Layer() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Layer* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Layer));
  }
#endif

  template <typename = void>
  explicit constexpr Layer(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline Layer(const Layer& from) : Layer(nullptr, from) {}
  inline Layer(Layer&& from) noexcept : Layer(nullptr, ::std::move(from)) {}
  inline Layer& operator=(const Layer& from) {
    CopyFrom(from);
    return *this;
  }
  inline Layer& operator=(Layer&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const Layer& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<Layer>(&Layer_globals_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Layer& a, Layer& b) { a.Swap(&b); }
  inline void Swap(Layer* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Layer* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] Layer* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Layer>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Layer& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Layer& from) { Layer::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Layer* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "nn_proto.Layer"; }

  explicit Layer(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Layer(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Layer& from);
  Layer(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Layer&& from) noexcept
      : Layer(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBFieldNumber = 3,
    kNeuronCountFieldNumber = 1,
    kActivationFieldNumber = 2,
  };
  // bytes b = 3;
  void clear_b() ;
  [[nodiscard]] const ::std::string& b() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_b(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_b();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_b();
  void set_allocated_b(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_b() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_b(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_b();

  public:
  // int32 neuron_count = 1;
  void clear_neuron_count() ;
  [[nodiscard]] ::int32_t neuron_count() const;
  void set_neuron_count(::int32_t value);

  private:
  ::int32_t _internal_neuron_count() const;
  void _internal_set_neuron_count(::int32_t value);

  public:
  // .nn_proto.ActivationType activation = 2;
  void clear_activation() ;
  [[nodiscard]] ::nn_proto::ActivationType activation() const;
  void set_activation(::nn_proto::ActivationType value);

  private:
  ::nn_proto::ActivationType _internal_activation() const;
  void _internal_set_activation(::nn_proto::ActivationType value);

  public:
  // @@protoc_insertion_point(class_scope:nn_proto.Layer)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<2, 3,
                          0, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Layer& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr b_;
    ::int32_t neuron_count_;
    int activation_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_network_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED Network final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:nn_proto.Network) */ {
 public:
  inline Network() : Network(nullptr) {}
  ~Network() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Network* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Network));
  }
#endif

  template <typename = void>
  explicit constexpr Network(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline Network(const Network& from) : Network(nullptr, from) {}
  inline Network(Network&& from) noexcept : Network(nullptr, ::std::move(from)) {}
  inline Network& operator=(const Network& from) {
    CopyFrom(from);
    return *this;
  }
  inline Network& operator=(Network&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const Network& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<Network>(&Network_globals_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(Network& a, Network& b) { a.Swap(&b); }
  inline void Swap(Network* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Network* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] Network* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Network>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Network& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Network& from) { Network::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Network* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "nn_proto.Network"; }

  explicit Network(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Network(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Network& from);
  Network(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Network&& from) noexcept
      : Network(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLayersFieldNumber = 2,
    kMetrixsFieldNumber = 3,
    kLayerCountFieldNumber = 1,
  };
  // repeated .nn_proto.Layer layers = 2;
  [[nodiscard]] int layers_size() const;
  private:
  int _internal_layers_size() const;

  public:
  void clear_layers() ;
  [[nodiscard]] const ::nn_proto::Layer& layers(int index) const;
  [[nodiscard]] ::nn_proto::Layer* PROTOBUF_NONNULL mutable_layers(int index);
  ::nn_proto::Layer* PROTOBUF_NONNULL add_layers();
  [[nodiscard]] const ::google::protobuf::RepeatedPtrField<::nn_proto::Layer>&
  layers() const;
  [[nodiscard]] ::google::protobuf::RepeatedPtrField<::nn_proto::Layer>* PROTOBUF_NONNULL
  mutable_layers();

  private:
  const ::google::protobuf::RepeatedPtrField<::nn_proto::Layer>& _internal_layers() const;
  ::google::protobuf::RepeatedPtrField<::nn_proto::Layer>* PROTOBUF_NONNULL _internal_mutable_layers();

  public:
  // repeated .nn_proto.WeightMetrix metrixs = 3;
  [[nodiscard]] int metrixs_size() const;
  private:
  int _internal_metrixs_size() const;

  public:
  void clear_metrixs() ;
  [[nodiscard]] const ::nn_proto::WeightMetrix& metrixs(int index) const;
  [[nodiscard]] ::nn_proto::WeightMetrix* PROTOBUF_NONNULL mutable_metrixs(int index);
  ::nn_proto::WeightMetrix* PROTOBUF_NONNULL add_metrixs();
  [[nodiscard]] const ::google::protobuf::RepeatedPtrField<::nn_proto::WeightMetrix>&
  metrixs() const;
  [[nodiscard]] ::google::protobuf::RepeatedPtrField<::nn_proto::WeightMetrix>* PROTOBUF_NONNULL
  mutable_metrixs();

  private:
  const ::google::protobuf::RepeatedPtrField<::nn_proto::WeightMetrix>& _internal_metrixs() const;
  ::google::protobuf::RepeatedPtrField<::nn_proto::WeightMetrix>* PROTOBUF_NONNULL _internal_mutable_metrixs();

  public:
  // int32 layer_count = 1;
  void clear_layer_count() ;
  [[nodiscard]] ::int32_t layer_count() const;
  void set_layer_count(::int32_t value);

  private:
  ::int32_t _internal_layer_count() const;
  void _internal_set_layer_count(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:nn_proto.Network)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<2, 3,
                          2, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Network& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::nn_proto::Layer > layers_;
    ::google::protobuf::RepeatedPtrField< ::nn_proto::WeightMetrix > metrixs_;
    ::int32_t layer_count_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_network_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// WeightMetrix

// int32 rows = 1;
inline void WeightMetrix::clear_rows() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rows_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline ::int32_t WeightMetrix::rows() const {
  // @@protoc_insertion_point(field_get:nn_proto.WeightMetrix.rows)
  return _internal_rows();
}
inline void WeightMetrix::set_rows(::int32_t value) {
  _internal_set_rows(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:nn_proto.WeightMetrix.rows)
}
inline ::int32_t WeightMetrix::_internal_rows() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rows_;
}
inline void WeightMetrix::_internal_set_rows(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rows_ = value;
}

// int32 cols = 2;
inline void WeightMetrix::clear_cols() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cols_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline ::int32_t WeightMetrix::cols() const {
  // @@protoc_insertion_point(field_get:nn_proto.WeightMetrix.cols)
  return _internal_cols();
}
inline void WeightMetrix::set_cols(::int32_t value) {
  _internal_set_cols(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:nn_proto.WeightMetrix.cols)
}
inline ::int32_t WeightMetrix::_internal_cols() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cols_;
}
inline void WeightMetrix::_internal_set_cols(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cols_ = value;
}

// bytes data = 3;
inline void WeightMetrix::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::std::string& WeightMetrix::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:nn_proto.WeightMetrix.data)
  return _internal_data();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void WeightMetrix::set_data(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:nn_proto.WeightMetrix.data)
}
inline ::std::string* PROTOBUF_NONNULL WeightMetrix::mutable_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:nn_proto.WeightMetrix.data)
  return _s;
}
inline const ::std::string& WeightMetrix::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_.Get();
}
inline void WeightMetrix::_internal_set_data(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL WeightMetrix::_internal_mutable_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.data_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE WeightMetrix::release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:nn_proto.WeightMetrix.data)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.data_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.data_.Set("", GetArena());
  }
  return released;
}
inline void WeightMetrix::set_allocated_data(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:nn_proto.WeightMetrix.data)
}

// -------------------------------------------------------------------

// Layer

// int32 neuron_count = 1;
inline void Layer::clear_neuron_count() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.neuron_count_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline ::int32_t Layer::neuron_count() const {
  // @@protoc_insertion_point(field_get:nn_proto.Layer.neuron_count)
  return _internal_neuron_count();
}
inline void Layer::set_neuron_count(::int32_t value) {
  _internal_set_neuron_count(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:nn_proto.Layer.neuron_count)
}
inline ::int32_t Layer::_internal_neuron_count() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.neuron_count_;
}
inline void Layer::_internal_set_neuron_count(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.neuron_count_ = value;
}

// .nn_proto.ActivationType activation = 2;
inline void Layer::clear_activation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.activation_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline ::nn_proto::ActivationType Layer::activation() const {
  // @@protoc_insertion_point(field_get:nn_proto.Layer.activation)
  return _internal_activation();
}
inline void Layer::set_activation(::nn_proto::ActivationType value) {
  _internal_set_activation(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:nn_proto.Layer.activation)
}
inline ::nn_proto::ActivationType Layer::_internal_activation() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::nn_proto::ActivationType>(_impl_.activation_);
}
inline void Layer::_internal_set_activation(::nn_proto::ActivationType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.activation_ = value;
}

// bytes b = 3;
inline void Layer::clear_b() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.b_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::std::string& Layer::b() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:nn_proto.Layer.b)
  return _internal_b();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Layer::set_b(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.b_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:nn_proto.Layer.b)
}
inline ::std::string* PROTOBUF_NONNULL Layer::mutable_b()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_b();
  // @@protoc_insertion_point(field_mutable:nn_proto.Layer.b)
  return _s;
}
inline const ::std::string& Layer::_internal_b() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.b_.Get();
}
inline void Layer::_internal_set_b(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.b_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Layer::_internal_mutable_b() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.b_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Layer::release_b() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:nn_proto.Layer.b)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.b_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.b_.Set("", GetArena());
  }
  return released;
}
inline void Layer::set_allocated_b(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.b_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.b_.IsDefault()) {
    _impl_.b_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:nn_proto.Layer.b)
}

// -------------------------------------------------------------------

// Network

// int32 layer_count = 1;
inline void Network::clear_layer_count() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.layer_count_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline ::int32_t Network::layer_count() const {
  // @@protoc_insertion_point(field_get:nn_proto.Network.layer_count)
  return _internal_layer_count();
}
inline void Network::set_layer_count(::int32_t value) {
  _internal_set_layer_count(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:nn_proto.Network.layer_count)
}
inline ::int32_t Network::_internal_layer_count() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.layer_count_;
}
inline void Network::_internal_set_layer_count(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.layer_count_ = value;
}

// repeated .nn_proto.Layer layers = 2;
inline int Network::_internal_layers_size() const {
  return _internal_layers().size();
}
inline int Network::layers_size() const {
  return _internal_layers_size();
}
inline void Network::clear_layers() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.layers_.Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::nn_proto::Layer& Network::layers(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:nn_proto.Network.layers)
  return _internal_layers().Get(index);
}
inline ::nn_proto::Layer* PROTOBUF_NONNULL Network::mutable_layers(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:nn_proto.Network.layers)
  return _internal_mutable_layers()->Mutable(index);
}
inline ::nn_proto::Layer* PROTOBUF_NONNULL Network::add_layers()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::nn_proto::Layer* _add =
      _internal_mutable_layers()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:nn_proto.Network.layers)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::nn_proto::Layer>& Network::layers() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:nn_proto.Network.layers)
  return _internal_layers();
}
inline ::google::protobuf::RepeatedPtrField<::nn_proto::Layer>* PROTOBUF_NONNULL
Network::mutable_layers() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:nn_proto.Network.layers)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_layers();
}
inline const ::google::protobuf::RepeatedPtrField<::nn_proto::Layer>&
Network::_internal_layers() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.layers_;
}
inline ::google::protobuf::RepeatedPtrField<::nn_proto::Layer>* PROTOBUF_NONNULL
Network::_internal_mutable_layers() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.layers_;
}

// repeated .nn_proto.WeightMetrix metrixs = 3;
inline int Network::_internal_metrixs_size() const {
  return _internal_metrixs().size();
}
inline int Network::metrixs_size() const {
  return _internal_metrixs_size();
}
inline void Network::clear_metrixs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.metrixs_.Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline const ::nn_proto::WeightMetrix& Network::metrixs(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:nn_proto.Network.metrixs)
  return _internal_metrixs().Get(index);
}
inline ::nn_proto::WeightMetrix* PROTOBUF_NONNULL Network::mutable_metrixs(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:nn_proto.Network.metrixs)
  return _internal_mutable_metrixs()->Mutable(index);
}
inline ::nn_proto::WeightMetrix* PROTOBUF_NONNULL Network::add_metrixs()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::nn_proto::WeightMetrix* _add =
      _internal_mutable_metrixs()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add:nn_proto.Network.metrixs)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::nn_proto::WeightMetrix>& Network::metrixs() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:nn_proto.Network.metrixs)
  return _internal_metrixs();
}
inline ::google::protobuf::RepeatedPtrField<::nn_proto::WeightMetrix>* PROTOBUF_NONNULL
Network::mutable_metrixs() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_list:nn_proto.Network.metrixs)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_metrixs();
}
inline const ::google::protobuf::RepeatedPtrField<::nn_proto::WeightMetrix>&
Network::_internal_metrixs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.metrixs_;
}
inline ::google::protobuf::RepeatedPtrField<::nn_proto::WeightMetrix>* PROTOBUF_NONNULL
Network::_internal_mutable_metrixs() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.metrixs_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace nn_proto


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::nn_proto::ActivationType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::nn_proto::ActivationType>() {
  return ::nn_proto::ActivationType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // network_2eproto_2epb_2eh
